version: '3.8'

services:
  nginx:
    image: nginx:stable-bullseye
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  backend:
    build: ./backend  # กลับมาใช้ build เพราะเราแก้โค้ดใหม่
    expose:
      - "8000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=counter_db
      - PLUGIN_HOST=plugin   # บอกชื่อเครื่อง Plugin
      - PLUGIN_PORT=50051
    depends_on:
      - db
      - plugin               # ต้องรอ Plugin ด้วย
    restart: always

  # ✅ เพิ่ม Service ใหม่: Plugin
  plugin:
    build: ./plugin
    expose:
      - "50051"
    restart: always

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: counter_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data: