version: '3.8'

services:
  # 1. Gateway (ตัวเข้างานหลัก Port 80)
  gateway:
    image: nginx:stable-bullseye
    ports:
      - "80:80"
    volumes:
      - ./nginx_gateway.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
      - history

  # 2. Frontend
  frontend:
    image: ter2004/counter-frontend:v1

  # 3. Backend
  backend:
    build: ./backend
    expose:
      - "8000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=counter_db
      - PLUGIN_HOST=plugin
      - PLUGIN_PORT=50051
      - RABBIT_HOST=rabbitmq
    depends_on:
      - db
      - plugin
      - rabbitmq
    restart: always

  # 4. Plugin
  plugin:
    image: ter2004/counter-plugin:P2
    expose:
      - "50051"
    restart: always

  # 5. Database (✅ เพิ่ม ports: 3306 แล้ว)
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: counter_db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"   # <--- บรรทัดนี้สำคัญครับ ทำให้ Workbench เข้าได้
    restart: always

  # 6. RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    restart: always

  # 7. History Service
  history:
    build: ./history
    expose:
      - "8001"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=counter_db
      - RABBIT_HOST=rabbitmq
    depends_on:
      - db
      - rabbitmq
    restart: always

volumes:
  mysql_data: